# Generated by Django 3.0.6 on 2020-07-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0002_pr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pr',
        ),
    ]
