# Generated by Django 3.0.6 on 2020-07-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0003_delete_pr'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerData',
            fields=[
                ('trainer_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('trainer_name', models.CharField(default='', max_length=40)),
                ('trainer_email', models.CharField(default='', max_length=40, unique=True)),
                ('trainer_about', models.CharField(default='', max_length=200)),
                ('trainer_img_name', models.CharField(default='tr.jpg', max_length=10)),
                ('trainer_contact', models.CharField(default='', max_length=20)),
                ('trainer_address', models.CharField(default='', max_length=100)),
                ('trainer_dob', models.CharField(default='', max_length=12)),
                ('trainer_height', models.CharField(default='', max_length=15)),
                ('trainer_weight', models.CharField(default='', max_length=10)),
                ('trainer_fb', models.CharField(default='', max_length=50)),
                ('trainer_ig', models.CharField(default='', max_length=50)),
                ('trainer_status', models.CharField(default='Active', max_length=10)),
                ('trainer_added_by', models.CharField(default='', max_length=10)),
                ('trainer_added_on', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
