# Generated by Django 3.0.6 on 2020-07-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0004_trainerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageData',
            fields=[
                ('package_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('package_name', models.CharField(default='', max_length=40, unique=True)),
                ('package_desc', models.CharField(default='', max_length=200)),
                ('package_features', models.TextField(default='')),
                ('package_price', models.IntegerField(default=0, max_length=20)),
                ('trainer_added_by', models.CharField(default='', max_length=10)),
                ('trainer_added_on', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
