# Generated by Django 3.0.6 on 2020-07-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0005_packagedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagedata',
            old_name='trainer_added_by',
            new_name='package_added_by',
        ),
        migrations.RenameField(
            model_name='packagedata',
            old_name='trainer_added_on',
            new_name='package_added_on',
        ),
    ]
