# Generated by Django 3.0.6 on 2020-07-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0006_auto_20200720_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentData',
            fields=[
                ('equipment_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(default='', max_length=40)),
                ('equipment_brand', models.CharField(default='', max_length=40)),
                ('equipment_price', models.IntegerField(default=0, max_length=20)),
                ('equipment_total', models.IntegerField(default=0, max_length=20)),
                ('equipment_added_by', models.CharField(default='', max_length=10)),
                ('equipment_added_on', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
