# Generated by Django 3.0.6 on 2020-07-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0007_equipmentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdata',
            name='equipment_quantity',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
