# Generated by Django 3.0.6 on 2020-07-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0008_equipmentdata_equipment_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassData',
            fields=[
                ('class_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('Class_name', models.CharField(default='', max_length=40)),
                ('class_desc', models.CharField(default='', max_length=200)),
                ('class_img_name', models.CharField(default='cls.jpg', max_length=10)),
                ('class_days', models.CharField(default='', max_length=70)),
                ('class_stime', models.CharField(default='', max_length=20)),
                ('class_etime', models.CharField(default='', max_length=20)),
                ('class_trainer', models.CharField(default='', max_length=10)),
                ('class_added_by', models.CharField(default='', max_length=10)),
                ('class_added_on', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
