# Generated by Django 3.0.6 on 2020-07-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0009_classdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classdata',
            old_name='Class_name',
            new_name='class_name',
        ),
    ]
