# Generated by Django 3.0.6 on 2020-07-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0010_auto_20200723_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseData',
            fields=[
                ('expense_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('expense_name', models.CharField(default='', max_length=40)),
                ('expense_price', models.IntegerField(default=0, max_length=20)),
                ('expense_month', models.CharField(default='', max_length=40)),
                ('expense_year', models.IntegerField(default=0, max_length=20)),
                ('expense_added_by', models.CharField(default='', max_length=10)),
                ('expense_added_on', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
