# Generated by Django 3.0.6 on 2020-07-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0011_expensedata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensedata',
            unique_together={('expense_name', 'expense_month', 'expense_year')},
        ),
    ]
