# Generated by Django 3.0.6 on 2020-07-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0012_auto_20200723_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedata',
            name='expense_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
