# Generated by Django 3.0.6 on 2020-07-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0013_auto_20200723_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseData',
            fields=[
                ('exercise_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('execise_name', models.CharField(default='', max_length=40)),
                ('exercise_desc', models.CharField(default='', max_length=200)),
                ('exercise_img_name', models.CharField(default='exr.jpg', max_length=10)),
                ('exercise_equipment', models.CharField(default='', max_length=50)),
                ('exercise_muscle', models.CharField(default='', max_length=200)),
                ('execise_sets', models.CharField(default='', max_length=40)),
                ('exercise_tutorial', models.CharField(default='', max_length=500)),
                ('exercise_added_by', models.CharField(default='', max_length=10)),
                ('exercise_added_on', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
