# Generated by Django 3.0.6 on 2020-07-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0014_exercisedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisedata',
            old_name='execise_name',
            new_name='exercise_name',
        ),
    ]
