# Generated by Django 3.0.6 on 2020-07-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0016_auto_20200723_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietData',
            fields=[
                ('diet_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('diet_name', models.CharField(default='', max_length=40)),
                ('diet_desc', models.CharField(default='', max_length=200)),
                ('diet_json', models.TextField(default='')),
                ('diet_added_by', models.CharField(default='', max_length=10)),
                ('diet_added_on', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
