# Generated by Django 3.0.6 on 2020-07-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0018_routinedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberData',
            fields=[
                ('member_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('member_package', models.CharField(default='pkg', max_length=10)),
                ('member_img_name', models.CharField(default='mem.jpg', max_length=10)),
                ('member_name', models.CharField(default='', max_length=40)),
                ('member_email', models.CharField(default='', max_length=40, unique=True)),
                ('member_contact', models.CharField(default='', max_length=20)),
                ('member_address', models.CharField(default='', max_length=100)),
                ('member_dob', models.CharField(default='', max_length=12)),
                ('member_height', models.CharField(default='', max_length=15)),
                ('member_weight', models.CharField(default='', max_length=10)),
                ('member_routine', models.CharField(default='rtn', max_length=10)),
                ('member_diet', models.CharField(default='dt', max_length=10)),
                ('member_status', models.CharField(default='Active', max_length=10)),
                ('member_added_by', models.CharField(default='', max_length=10)),
                ('member_added_on', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
