# Generated by Django 3.0.6 on 2020-07-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0019_memberdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdata',
            name='member_password',
            field=models.CharField(default='admin123', max_length=200),
        ),
    ]
