# Generated by Django 3.0.6 on 2020-07-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0020_memberdata_member_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedata',
            name='package_admission',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
