# Generated by Django 3.0.6 on 2020-07-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0021_packagedata_package_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindata',
            name='admin_added_by',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='admin_added_on',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='admin_address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='admin_contact',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='admin_dob',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='admin_email',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='admin_id',
            field=models.CharField(default='', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='admin_img_name',
            field=models.CharField(default='adm.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='admin_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='admin_password',
            field=models.CharField(default='admin5003', max_length=500),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='admin_role',
            field=models.CharField(default='Admin', max_length=500),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='admin_status',
            field=models.CharField(default='Active', max_length=500),
        ),
        migrations.AlterField(
            model_name='classdata',
            name='class_added_by',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='classdata',
            name='class_added_on',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='classdata',
            name='class_days',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='classdata',
            name='class_desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='classdata',
            name='class_etime',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='classdata',
            name='class_id',
            field=models.CharField(default='', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classdata',
            name='class_img_name',
            field=models.CharField(default='cls.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='classdata',
            name='class_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='classdata',
            name='class_stime',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='classdata',
            name='class_trainer',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='dietdata',
            name='diet_added_by',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='dietdata',
            name='diet_added_on',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='dietdata',
            name='diet_desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='dietdata',
            name='diet_id',
            field=models.CharField(default='', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dietdata',
            name='diet_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='equipment_added_by',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='equipment_added_on',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='equipment_brand',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='equipment_id',
            field=models.CharField(default='', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='equipment_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='equipment_price',
            field=models.IntegerField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='equipment_quantity',
            field=models.IntegerField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='equipment_total',
            field=models.IntegerField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='exercisedata',
            name='exercise_added_by',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercisedata',
            name='exercise_added_on',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercisedata',
            name='exercise_desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercisedata',
            name='exercise_equipment',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercisedata',
            name='exercise_id',
            field=models.CharField(default='', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exercisedata',
            name='exercise_img_name',
            field=models.CharField(default='exr.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercisedata',
            name='exercise_muscle',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercisedata',
            name='exercise_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercisedata',
            name='exercise_sets',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='expensedata',
            name='expense_added_by',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='expensedata',
            name='expense_added_on',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='expensedata',
            name='expense_id',
            field=models.CharField(default='', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expensedata',
            name='expense_month',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='expensedata',
            name='expense_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='expensedata',
            name='expense_price',
            field=models.IntegerField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='expensedata',
            name='expense_year',
            field=models.IntegerField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='member_added_by',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='member_added_on',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='member_address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='member_contact',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='member_diet',
            field=models.CharField(default='dt', max_length=500),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='member_dob',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='member_email',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='member_height',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='member_id',
            field=models.CharField(default='', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='member_img_name',
            field=models.CharField(default='mem.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='member_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='member_package',
            field=models.CharField(default='pkg', max_length=500),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='member_password',
            field=models.CharField(default='admin5003', max_length=500),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='member_routine',
            field=models.CharField(default='rtn', max_length=500),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='member_status',
            field=models.CharField(default='Active', max_length=500),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='member_weight',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='package_added_by',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='package_added_on',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='package_admission',
            field=models.IntegerField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='package_desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='package_id',
            field=models.CharField(default='', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='package_name',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='package_price',
            field=models.IntegerField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='routinedata',
            name='routine_added_by',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='routinedata',
            name='routine_added_on',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='routinedata',
            name='routine_desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='routinedata',
            name='routine_id',
            field=models.CharField(default='', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='routinedata',
            name='routine_img_name',
            field=models.CharField(default='rt.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='routinedata',
            name='routine_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='trainer_about',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='trainer_added_by',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='trainer_added_on',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='trainer_address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='trainer_contact',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='trainer_dob',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='trainer_email',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='trainer_fb',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='trainer_height',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='trainer_id',
            field=models.CharField(default='', max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='trainer_ig',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='trainer_img_name',
            field=models.CharField(default='tr.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='trainer_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='trainer_status',
            field=models.CharField(default='Active', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='trainer_weight',
            field=models.CharField(default='', max_length=500),
        ),
    ]
