# Generated by Django 3.0.6 on 2020-07-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0024_archivedmessagedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyMessageData',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('msg_sender_name', models.CharField(default='', max_length=500)),
                ('msg_sender_email', models.CharField(default='', max_length=500)),
                ('msg_sender_time', models.CharField(default='', max_length=500)),
                ('msg_sender_date', models.CharField(default='', max_length=500)),
                ('msg_sender_subject', models.CharField(default='', max_length=500)),
                ('msg_sender_mail', models.TextField(default='')),
                ('msg_reciever_name', models.CharField(default='', max_length=500)),
                ('msg_reciever_email', models.CharField(default='', max_length=500)),
                ('msg_reciever_time', models.CharField(default='', max_length=500)),
                ('msg_reciever_date', models.CharField(default='', max_length=500)),
                ('msg_reciever_mail', models.TextField(default='')),
            ],
        ),
    ]
