# Generated by Django 3.0.6 on 2020-07-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0025_replymessagedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceData',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_member_id', models.CharField(default='', max_length=500)),
                ('attendance_in_time', models.CharField(default='', max_length=500)),
                ('attendance_out_time', models.CharField(default='', max_length=500)),
                ('attendance_day', models.CharField(default='', max_length=500)),
                ('attendance_date', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
