# Generated by Django 3.0.6 on 2020-07-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0027_attendancedata_attendance_member_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceData',
            fields=[
                ('finance_id', models.AutoField(primary_key=True, serialize=False)),
                ('finance_member_id', models.CharField(default='', max_length=500)),
                ('finance_member_name', models.CharField(default='', max_length=500)),
                ('finance_desc', models.CharField(default='', max_length=500)),
                ('finance_month', models.CharField(default='', max_length=500)),
                ('finance_year', models.CharField(default='', max_length=500)),
                ('finance_balance', models.IntegerField(default=0)),
                ('finance_due', models.IntegerField(default=0)),
            ],
        ),
    ]
