# Generated by Django 3.0.6 on 2020-07-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0028_financedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceHistoryData',
            fields=[
                ('fh_id', models.AutoField(primary_key=True, serialize=False)),
                ('fh_member_id', models.CharField(default='', max_length=500)),
                ('fh_member_name', models.CharField(default='', max_length=500)),
                ('fh_desc', models.CharField(default='', max_length=500)),
                ('fh_month', models.CharField(default='', max_length=500)),
                ('fh_year', models.CharField(default='', max_length=500)),
                ('fh_balance', models.IntegerField(default=0)),
                ('fh_due', models.IntegerField(default=0)),
                ('fh_recieved', models.IntegerField(default=0)),
                ('fh_added_by', models.CharField(default='', max_length=500)),
                ('fh_added_on', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
