# Generated by Django 3.0.6 on 2020-07-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0029_financehistorydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionData',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_package', models.CharField(default='pkg', max_length=500)),
                ('ad_name', models.CharField(default='', max_length=500)),
                ('ad_email', models.CharField(default='', max_length=500, unique=True)),
                ('ad_contact', models.CharField(default='', max_length=500)),
                ('ad_date', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
